PATH:
  FUNCLATENCY_PATH: meshinsight/profiler/latency/funclatency.py
  FUNCLATENCY_FILTER_PATH: meshinsight/profiler/latency/funclatency_filter.py
  SYSCALL_PATH: meshinsight/profiler/latency/syscall.c
  PROFILE_PATH: meshinsight/profiler/cpu/profile.py
  STACKCOLLAPSE_PATH: meshinsight/profiler/cpu/stackcollapse-perf.pl
  FLAMEGRAPH_PATH: meshinsight/profiler/cpu/flamegraph.pl
